/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mechanic */

#ifndef _Included_Mechanic
#define _Included_Mechanic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mechanic
 * Method:    initializeGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mechanic_initializeGame
        (JNIEnv *, jobject);

/*
 * Class:     Mechanic
 * Method:    isMoveValid
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Mechanic_isMoveValid
        (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Mechanic
 * Method:    makeMove
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_Mechanic_makeMove
        (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Mechanic
 * Method:    checkWin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Mechanic_checkWin
        (JNIEnv *, jobject);

/*
 * Class:     Mechanic
 * Method:    getCheckerAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Mechanic_getCheckerAt
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Mechanic
 * Method:    getCurrentPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Mechanic_getCurrentPlayer
        (JNIEnv *, jobject);

/*
 * Class:     Mechanic
 * Method:    getWhiteWins
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Mechanic_getWhiteWins
        (JNIEnv *, jobject);

/*
 * Class:     Mechanic
 * Method:    getBlackWins
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Mechanic_getBlackWins
        (JNIEnv *, jobject);

/*
 * Class:     Mechanic
 * Method:    endTurn
 * Signature: ()I
 */

#ifdef __cplusplus
}
#endif
#endif
